### ISSUE TITLE
CRT _timezone undefind reference issue on 64-bit windows

### ISSUE THREAD

**Issue by mudhairless** [freebasic/fbc#356]
This short example fails to compile with 1.09 on win64
```
#include once "crt/time.bi"

? _timezone
```

Error:
```
C:\FreeBASIC\bin\win64\ld.exe: fbc-issue.o:fake:(.rdata$.refptr._imp___timezone[.refptr._imp___timezone]+0x0): undefined reference to _imp___timezone'
```

I found a similar issue here:  [       // mingw's msvcrt is a weird hybrid import library and static library.](https://github.com/kennytm/rust/blob/eaa7a1fee84a9dfe92e9ba47ec72bdfc7550b579/src/librustc_back/target/windows_base.rs#L62) that indicates fbc may need to add msvcrt to LD's commandline twice so that it get the static and import parts. 

32bit compiler on windows (or building for 32bit) is not affected.
